language: php

sudo: false

php:
  - 7.1
  - 7.3

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

  fast_finish: true

  allow_failures:
    - php: 7.1
    - php: 7.3    

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run ; fi
  - if [[ $PHPCS == 1 ]]; then composer cs-check ; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
    email: false
