language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.3
      env: VALIDATION=1 DEFAULT=0

    - php: 7.4
      env: VALIDATION=1 DEFAULT=0

  fast_finish: true

  allow_failures:
    - php: 7.3
    - php: 7.4

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run ; fi
  - if [[ $VALIDATION == 1 ]]; then composer cs-check ; fi
  - if [[ $VALIDATION == 1 ]]; then composer phpstan-setup && composer phpstan ; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
    email: false
